Feature/refactor packages
nossas/mapa-do-acolhimento pull request #86
Opened 2021-12-10 01:01 UTC by lpirola

2021-12-15 15:06 UTC, igr-santos requested changes
Me parece um problema de lint nos tests, como se os  tests no CI esperassem uma configuração diferente dos tests local, pois localmente os tests rodam com sucesso e no log do CI dá um problema https://ci.bonde.org/nossas/mapa-do-acolhimento/357/3

2021-12-15 23:26 UTC, dieh reviewed
Consegui rodar o lint, test e build localmente. Tentei rodar o cli no mda-start e parece que deu erro na conexão com o elastic search, usando as configurações me staging. Posso ajudar amanhã a investigar melhor

2021-12-16 14:49 UTC, lpirola commented
Ficou decidido que por causa dos problemas com import dinâmico do node-zendesk, iremos remover ele do projeto.

2022-06-06 14:22 UTC, lpirola commented
@dieh agora é preciso atualizar a integração contínua para o github actions e migrar do drone?

2022-06-06 14:24 UTC, dieh commented
> @dieh agora é preciso atualizar a integração contínua para o github actions e migrar do drone?

isso :)

2022-06-06 19:39 UTC, lpirola commented
@dieh fiz o merge do main, a mim pareceu ok https://github.com/nossas/mapa-do-acolhimento/pull/92

Fiquei pensando no que precisamos para fazer deploy em staging:
- [ ] atualizar integração contínua para usar github actions e enviar imagem docker com build
- [ ] criar um stack mapa do acolhimento no bonde-install usando a nova imagem

2023-12-07 18:42 UTC, closed without merging